### PR TITLE
run analytics in background

### PR DESCRIPTION
**Pull request by aaronnorrish**
Previously, the front-end would wait on the back-end to complete the analytics computation (it would send off the request and wait for it to return.) Instead the analytics are now run in the background when the snapshot is created and then saved to the db once it has completed. The front-end will request the analytics whenever the user clicks on the "open snapshot analytics" button; if the analytics have completed, the results will be sent back, otherwise the front-end will be notified the computation is still in progress.

### CODE REVIEW

**Comment by aaronnorrish** [comment]
The back-end side of it is working, however, now that I made some more changes there seems to be something wrong with the front-end. For some reason, the analytics results are not being returned upon request (it will always say "In Progress" -- even when they definitely have been completed) when you create the snapshot and try to retrieve the results. When you navigate away to another snapshot and come back, the results will load correctly.

**Comment by aaronnorrish** [comment]
Also, the error handling is not optimal. Because the analytics are running in the background, any raised errors are just being ignored. In order to propagate this information to the front-end, I made the status of the analytics computation a field of the snapshot. In this way, we can tell when an error has occurred as opposed to just assuming that the analytics are still being computed. It doesn't seem like the ideal way of dealing with this though.

**Comment by Sothatsit** [comment]
> The back-end side of it is working, however, now that I made some more changes there seems to be something wrong with the front-end. For some reason, the analytics results are not being returned upon request (it will always say "In Progress" -- even when they definitely have been completed) when you create the snapshot and try to retrieve the results. When you navigate away to another snapshot and come back, the results will load correctly.

The frontend only requests the analytics data when the React state changes for the snapshot sidebar. In order for this to work, I think we'd need a timer that repeats the request after a few seconds if the analytics data is not yet available (and not errored).

See: https://github.com/PubMedConnections/PubMedConnections/blob/feature/refactor-analytics/web/src/components/graph/SnapshotSidebar.jsx#L156-L167



> Also, the error handling is not optimal. Because the analytics are running in the background, any raised errors are just being ignored. In order to propagate this information to the front-end, I made the status of the analytics computation a field of the snapshot. In this way, we can tell when an error has occurred as opposed to just assuming that the analytics are still being computed. It doesn't seem like the ideal way of dealing with this though.

As long as the error is logged to the console as well (e.g., `traceback.print_exc()` in the except block), then I think this is a good way to handle it.

**Comment by aaronnorrish** [comment]
> > The back-end side of it is working, however, now that I made some more changes there seems to be something wrong with the front-end. For some reason, the analytics results are not being returned upon request (it will always say "In Progress" -- even when they definitely have been completed) when you create the snapshot and try to retrieve the results. When you navigate away to another snapshot and come back, the results will load correctly.
> 
> The frontend only requests the analytics data when the React state changes for the snapshot sidebar. In order for this to work, I think we'd need a timer that repeats the request after a few seconds if the analytics data is not yet available (and not errored).
> 
> See: https://github.com/PubMedConnections/PubMedConnections/blob/feature/refactor-analytics/web/src/components/graph/SnapshotSidebar.jsx#L156-L167

Ahhh ok I see it now. Wouldn't it be simpler to try and retrieve the analytics results when the user clicks the "open snapshot analytics" button? If they're not complete, we can just have a message like "analytics not complete, please try again later" in the modal. Or is this not user friendly?

**Comment by pproe** [comment]
> Ahhh ok I see it now. Wouldn't it be simpler to try and retrieve the analytics results when the user clicks the "open snapshot analytics" button? If they're not complete, we can just have a message like "analytics not complete, please try again later" in the modal. Or is this not user friendly?

Although not the most ideal solution, I think this is more user-friendly than the current system at least.

**Comment by aaronnorrish** [comment]
> > Ahhh ok I see it now. Wouldn't it be simpler to try and retrieve the analytics results when the user clicks the "open snapshot analytics" button? If they're not complete, we can just have a message like "analytics not complete, please try again later" in the modal. Or is this not user friendly?
> 
> Although not the most ideal solution, I think this is more user-friendly than the current system at least.

Is what Paddy suggested (use a timer) a better way?

**Comment by pproe** [comment]
As far as I can see, there are 3 solutions we could use:
1. Aforementioned implementation (sending request when analytics is accessed and asking user to try again soon)
- Easiest to implement, maybe not the best user interaction.
2. Reattempting request on a schedule (every 10-20 seconds) and updating UI to reflect when analytics are done loading.
- Would require tracking of all currently 'loading' analytics and system to manage requests.
- No modifications to the API needed.
- Might overload server with requests if lots of analytics are loading at once.
3. Restructure API to track existing analytics and implement system where web app can subscribe to a certain transaction to get notified when the analytic is complete.
- Probably too much to change if we are looking for a quick solution.

Since we are on a bit of a time-crunch to get this out, I think number 1 might be our best option as its the easiest to implement and has less moving parts that could cause more unintended consequences. If I've missed any solutions please let me know!

**Comment by aaronnorrish** [comment]
I'd agree, given the time constraints, the first option seems like the best.

**Review by Jai-C — APPROVED** [review]
Looking good, I have tested it and it works for me.

**Pull request merged**
